export const designTokens = {
  color: {
    primitive: {
      neutral: {
        0: '#ffffff',
        100: '#f5f7fa',
        200: '#eceef4',
        300: '#d2d5e2',
        400: '#b6bccd',
        500: '#9ea5bd',
        600: '#79829f',
        700: '#626981',
        800: '#4b5162',
        900: '#343844',
        1000: '#1c1f25',
      },
      primary: {
        200: '#b6d1fb',
        600: '#387ff5',
        700: '#2d66c4',
        800: '#224c93',
      },
      primaryAlpha: { '05': '#387ff50d', 30: '#387ff54d' },
      neutralAlpha: { 10: '#ffffff1a', 20: '#ffffff33', 60: '#ffffff99' },
      darkOverlayElement: { 100: '#ffffff' },
    },
    semantic: {
      background: {
        primary: '{color.primitive.neutral.0}',
        muted: '{color.primitive.neutral.100}',
        disabled: '{color.primitive.neutral.200}',
        inverse: '{color.primitive.neutral.1000}',
      },
      foreground: {
        default: '{color.primitive.neutral.900}',
        muted: '{color.primitive.neutral.600}',
        subtle: '{color.primitive.neutral.700}',
        inverse: '{color.primitive.darkOverlayElement.100}',
      },
      border: {
        default: '{color.primitive.neutral.400}',
        strong: '{color.primitive.neutral.700}',
        focus: '{color.primitive.neutral.900}',
      },
      interactive: {
        primary: '{color.primitive.primary.600}',
        hover: '{color.primitive.primary.700}',
        focus: '{color.primitive.primary.800}',
        disabled: '{color.primitive.neutral.200}',
      },
    },
  },
  typography: {
    fontFamily: { heading: 'DM Sans', body: 'Inter' },
    fontWeight: { regular: 400, medium: 500, semibold: 600, bold: 700 },
    styles: {
      headingH1: { fontSize: '64px', lineHeight: '1.1', fontWeight: 700 },
      headingH2: { fontSize: '52px', lineHeight: '1.15', fontWeight: 700 },
      headingH3: { fontSize: '40px', lineHeight: '1.2', fontWeight: 700 },
      headingH4: { fontSize: '32px', lineHeight: '1.3', fontWeight: 700 },
      headingH5: { fontSize: '20px', lineHeight: '1.42', fontWeight: 700 },
      headingH6: { fontSize: '18px', lineHeight: '1.42', fontWeight: 700 },
      bodySmRegular: { fontSize: '14px', lineHeight: '1.4', fontWeight: 400 },
      bodyBaseRegular: { fontSize: '16px', lineHeight: '1.6', fontWeight: 400 },
      bodyBaseSemibold: {
        fontSize: '16px',
        lineHeight: '1.6',
        fontWeight: 600,
      },
      bodyMdMedium: { fontSize: '20px', lineHeight: '1.58', fontWeight: 500 },
      bodyLgRegular: { fontSize: '24px', lineHeight: '1.6', fontWeight: 400 },
      buttonSmBold: { fontSize: '14px', lineHeight: '1.26', fontWeight: 700 },
      buttonBaseBold: { fontSize: '16px', lineHeight: '1.22', fontWeight: 700 },
      navigationBaseMedium: {
        fontSize: '16px',
        lineHeight: '1.26',
        fontWeight: 500,
      },
      navigationMdMedium: {
        fontSize: '20px',
        lineHeight: '1.22',
        fontWeight: 500,
      },
      heroHeadingMobile: {
        fontSize: '38px',
        lineHeight: '1.16',
        fontWeight: 700,
      },
      heroHeadingDesktop: {
        fontSize: '48px',
        lineHeight: '1.16',
        fontWeight: 700,
      },
    },
    letterSpacing: { default: '0em' },
  },
  spacing: {
    primitive: {
      0: '0px',
      4: '4px',
      8: '8px',
      12: '12px',
      16: '16px',
      20: '20px',
      24: '24px',
      32: '32px',
      40: '40px',
      48: '48px',
      64: '64px',
      96: '96px',
    },
    semantic: {
      inline: {
        xs: '{spacing.primitive.4}',
        xl: '{spacing.primitive.20}',
        '3xl': '{spacing.primitive.32}',
      },
      inset: {
        sm: '{spacing.primitive.8}',
        md: '{spacing.primitive.12}',
        lg: '{spacing.primitive.16}',
        xl: '{spacing.primitive.20}',
        '3xl': '{spacing.primitive.32}',
        '4xl': '{spacing.primitive.40}',
      },
      stack: {
        sm: '{spacing.primitive.8}',
        lg: '{spacing.primitive.16}',
        xl: '{spacing.primitive.20}',
        '2xl': '{spacing.primitive.24}',
      },
      section: {
        sm: '{spacing.primitive.48}',
        md: '{spacing.primitive.64}',
        lg: '{spacing.primitive.96}',
      },
    },
  },
  radius: {
    md: '8px',
    lg: '12px',
    xl: '16px',
    '2xl': '20px',
    '3xl': '24px',
    '4xl': '32px',
  },
  effect: {
    shadowPrimary1:
      '0 6px 8px #387ff50d, 0 9px 12px #387ff50d, 0 16px 10px #387ff50d',
    shadowPrimary4:
      '0 2px 6px #387ff54d, 0 13px 12px #387ff50d, 0 24px 15px #387ff50d, 0 40px 16px #387ff50d, 0 62px 17px #387ff50d',
    shadowEyebrow:
      '0 10px 18px #3a4c921a, 0 2px 6px #2c3a720d, 0 0 1px #2c3a720d',
    blurButton: '6px',
  },
  breakpoint: {
    mobile: '420px',
    tablet: '768px',
    navigationDesktop: '1024px',
    desktop: '1440px',
  },
  grid: {
    mobile: { width: '420px', columns: 4, margin: '20px', gutter: '16px' },
    tablet: { width: '810px', columns: 8, margin: '32px', gutter: '20px' },
    desktop: { width: '1440px', columns: 12, margin: '120px', gutter: '24px' },
  },
  // Existing CSS-only foundation values, centralized without changing their values.
  control: { sm: '36px', md: '44px', lg: '48px' },
  icon: { sm: '18px', md: '20px', lg: '24px' },
  outline: { offset: '2px', width: '2px' },
  border: { width: '1px' },
  container: {
    'content-sm': '640px',
    'content-md': '810px',
    content: '1200px',
  },
  component: {
    navbar: {
      mobileHeight: '68px',
      tabletHeight: '76px',
      mobileOpenHeight: '452px',
      tabletOpenHeight: '460px',
      desktopHeight: '122px',
      contentWidth: '1204px',
      utilityHeight: '38px',
      mainHeight: '84px',
      mobileInset: '10px',
      tabletInset: '14px',
      logoWidth: '114px',
      logoHeight: '32px',
      demoWidth: '128px',
      trialWidth: '179px',
      trailingSlot: '48px',
      menuHeight: '384px',
      menuItemHeight: '64px',
    },
    hero: {
      contentWidth: '860px',
      contentMobileHeight: '506px',
      contentTabletHeight: '390px',
      contentDesktopHeight: '334px',
      textMobileHeight: '362px',
      textTabletHeight: '302px',
      textDesktopHeight: '246px',
      desktopTopInset: '112px',
      desktopBottomInset: '80px',
      mobileVerticalInset: '60px',
      desktopGap: '60px',
      descriptionInset: '80px',
      screenDesktopHeight: '480px',
      screenMobileHeight: '267px',
      trialWidth: '205px',
      watchTabletWidth: '160px',
      watchDesktopWidth: '178px',
      videoCardWidth: '350px',
      videoCardHeight: '108px',
      videoButtonMobile: '108px',
    },
    socialProof: {
      contentWidth: '1204px',
      mobileVerticalInset: '48px',
      desktopVerticalInset: '80px',
      headingWidth: '680px',
      logoHeight: '32px',
    },
    strategies: {
      contentWidth: '1204px',
      mobileVerticalInset: '64px',
      desktopVerticalInset: '96px',
      headerWidth: '720px',
      cardMinHeight: '244px',
      visualMobileHeight: '360px',
      visualTabletHeight: '400px',
      visualDesktopHeight: '430px',
      visualCopyWidth: '390px',
      metricCardWidth: '184px',
      metricCardHeight: '112px',
      chartLineWidth: '210px',
      chartLineHeight: '3px',
      chartPointSize: '12px',
      gridSize: '72px',
    },
    testimonials: {
      contentWidth: '1204px',
      mobileVerticalInset: '64px',
      desktopVerticalInset: '96px',
      headerWidth: '720px',
      cardMinHeight: '272px',
      avatarSize: '48px',
    },
    trialCta: {
      contentWidth: '1204px',
      mobileVerticalInset: '48px',
      desktopVerticalInset: '80px',
      panelMobileInset: '32px',
      panelDesktopInset: '60px',
      panelDesktopMinHeight: '424px',
      copyWidth: '568px',
      benefitsWidth: '381px',
      benefitHeight: '88px',
      iconWidth: '48px',
      iconHeight: '72px',
      buttonWidth: '253px',
      buttonHeight: '56px',
      patternWidth: '879px',
    },
    applications: {
      contentWidth: '1204px',
      mobileVerticalInset: '64px',
      desktopVerticalInset: '96px',
      headerWidth: '720px',
      cardMinHeight: '300px',
      visualHeight: '128px',
      chartBarWidth: '28px',
    },
    footer: {
      contentWidth: '1204px',
      mobileVerticalInset: '48px',
      desktopVerticalInset: '64px',
      brandWidth: '320px',
      logoWidth: '114px',
      logoHeight: '32px',
    },
  },
  columns: { 1: 1, 2: 2, 3: 3, 4: 4, 8: 8, 12: 12 },
} as const;

export type DesignTokens = typeof designTokens;
export const tokens = designTokens;
export type Tokens = typeof tokens;
